### ISSUE TITLE
xmllint does not resolve keyrefs

### ISSUE THREAD

**Issue by Nemo64** [emgdev/xml-import#56]
I tried to validate an xml using `xmllint` because it is pre installed on a mac.

I already found the #55 issue but there is another one. It can't resolve keyref's for some reason. Even the example fails.

`xmllint --schema schemas/3.0/xml-import.xsd --noout samples/3.0/event-sample.xml`

I read a bit and it seems to be issues when the types don't match but i could not get it to work.

Some idea?
What is the recommended way to validate the xml?

**Comment by Kralizek** [comment]
Hi @Nemo64, thanks for reporting your problem.

We have developed a online application to test XML feeds.

Please consider that this is still in beta.... 

Let me know if this helps you: https://xml-validator.educationsmediagroup.com

**Comment by Nemo64** [comment]
It says: "Your file matched the EMGXML30 schema and the **import is done**.". I hope it was just a validation and not a real import somewhere? But as a validator, it works.

I'd prefer if I could use the schema locally though. For xmllint, it seems to be a bad implementation on their part: https://mail.gnome.org/archives/xml/2005-August/msg00087.html although for all other validations it's fine.

For documentation purposes, this is how to validate while ignoring keyref's:
`xmllint --schema xml-import-master/schemas/3.0/xml-import.xsd --noout xml-import-master/samples/3.0/event-sample.xml 2>&1|grep -v 'No match found for key-sequence'`

**Comment by Kralizek** [comment]
Hi! It's just a validator we have created for our customers and the third-party developers working for them to test their files using exactly the same code we will then use before executing the real import.
